---

apiVersion: v1
kind: Service
metadata:
  name: front-end-cluster-srv 
spec:
  type: ClusterIP
  selector:
    app: myapp
    type: front-end 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
