---

apiVersion: v1
kind: Service
metadata:
  name: my-srv
spec:
  selector:
    app: myapp
    type: front-end 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30009
  type: LoadBalancer
