---

apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: NodePort
  selector:
    app: myapp
    type: front-end 
  ports:
  - protocol: TCP
    port: 80
    #targetPort: 80
    nodePort: 30008



#kind: Service
#apiVersion: v1
#metadata:
#  name: my-service
#spec:
#  selector:
#    app: myapp
#  ports:
#  - protocol: TCP
#    port: 3000
#    nodePort: 32321
#  type: NodePort
