---
apiVersion: v1
kind: Pod
metadata:
  name: container-nginx  
  labels:
    app: nginx-app
    function: backend
    env: prd
    bu: devops
spec:
  containers:
  - name: nginx-container 
    image: nginx
    ports:
    - name: web-server
      protocol: TCP 
      containerPort: 80  
   
